### ISSUE TITLE
[오타] 19.cpp

### ISSUE THREAD

**Issue by bible-highting** [dremdeveloper/codingtest_cpp#1]
안녕하세요 골든래빗 김성경입니다!

https://github.com/dremdeveloper/codingtest_cpp/blob/main/solution/19.cpp

37번째 줄 오타가 있습니다.

[as-is] 

```
   // ❹ quer_list들이 hash에 있는지에 대한 값이 있는지에 대한 결과가 저장된 result를 반환
```

[to-be] 
```
   // ❹ query_list의 문자열이 hash에 있는지 결과가 저장된 result를 반환
```

테스트 겸 남겨보았습니다!
앞으로 이렇게 코드에 중요한 오타가 보이면 이슈로 남겨놓겠습니다~

**Comment by dremdeveloper** [comment]
수정했습니다 감사합니다^^
