### ISSUE TITLE
[수정 요청] 67.cpp

### ISSUE THREAD

**Issue by bible-highting** [dremdeveloper/codingtest_cpp#4]
책의 색상 변경으로 인해 설명을 변경했습니다.

* 파란색 ➝ 초록색
* blue ➝ green

정답 코드에도 해당 매개변수, 설명을 변경해야 할 것 같아서 이슈 남겨놓습니다.
https://github.com/dremdeveloper/codingtest_cpp/blob/main/solution/67.cpp

**Comment by dremdeveloper** [comment]
이슈 해결 완료했습니다.
