### ISSUE TITLE
[수정 요청] 40.cpp

### ISSUE THREAD

**Issue by bible-highting** [dremdeveloper/codingtest_cpp#5]
https://github.com/dremdeveloper/codingtest_cpp/blob/main/solution/40.cpp

maze ➝ maps 일괄 변경

---

선생님
교정 보다보니 문제 40번에서 입출력의 예는 배열 이름이 maps인데
프로토타입부터 코드 설명까지는 maze로 변수명을 사용해서 
프로그래머스 기준인 maps로 통일했습니다.

사소한 이슈지만 여기도 동기화 하면 좋을 것 같아서 이슈남깁니다.

**Comment by dremdeveloper** [comment]
이슈 해결 완료했습니다.
